name: 3D Skyline
on:
  schedule: [{ cron: "30 0 * * *" }]
  workflow_dispatch:
  push: { branches: [ "main", "master" ] }
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
      - run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add -A .
          git commit -m "regenerate 3D skyline" || echo "no changes"
          git push
