name: Latest Blog Posts
on:
  schedule: [{ cron: "0 */12 * * *" }]
  workflow_dispatch:
permissions:
  contents: write
jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://dev.to/feed/tarunmehrda"   # 👈 replace with YOUR Dev.to / Medium / Hashnode RSS
